### ISSUE TITLE
Available Jobs page doesn't show which queue each job belongs to

### ISSUE THREAD

**Issue by eric116** [Hoektronics/BotQueue#135]
In the available jobs box at the bottom of the main page, you can see the job's file name and which queue it belongs to. However, when you click on 'Show All', there's a column for which bot the job belongs to, which is always N/A since a worker bee hasn't taken it yet. It would be nice if it showed which queue it belongs to instead.

**Comment by Jnesselr** [comment]
Right now, a Job is only in one queue, so I just made that change and pushed it up. In the next version, you can specify a job to be in any amount of queues without having to create a queue encompassing those bots specifically. This means a job, much like a bot is now, will be able to be in multiple queues.
