### ISSUE TITLE
Working Jobs references pending jobs on Queues page

### ISSUE THREAD

**Issue by StanleyT** [Hoektronics/BotQueue#142]
watching a specific queue by its direct page, the "Working Jobs" section is looking for pending jobs and does not correctly indicate a working job
![screenshot-09292015](https://cloud.githubusercontent.com/assets/12972949/10174310/6b42e988-66a6-11e5-9e9b-2d21b7821bc8.png)

**Comment by Jnesselr** [comment]
What do you mean it's looking for pending jobs? Current master shows that it's grabbing jobs with the status of 'taken'. Obviously there are some bots with the status of working, so the jobs should be 'taken'. Hmm. Let's find out: (Note, I have no server I can access right now to test this query)

SELECT b.name, b.status, j.name, j.status
FROM bot b
JOIN job j
ON b.job_id = j.id
WHERE b.status='working';

This should give a list of bots that are currently working and their job status. The job status should be 'taken'. Please let me know what it is, if it isn't that.

**Comment by StanleyT** [comment]
looking closer into the issue, it appears to only be affecting that one queue.  other queues are reporting correctly. oddly enough queue Y is a subset of queue -MINI- and although Y does not show the jobs correctly, -MINI- has them correctly displayed...

![screenshot-09292015-2](https://cloud.githubusercontent.com/assets/12972949/10175757/e8f07574-66ad-11e5-92f0-9d1b8d8dd782.png)

I can try to get the script ran if you still think it is relevant

**Comment by Jnesselr** [comment]
Oh interesting. Okay, so the job is running out of mini not Y, meaning that
it won't show up in Y.

Basically, Y has no working jobs. Y has bots that are working, but they're
not working on jobs that are in Y.

**Comment by StanleyT** [comment]
queue Z is a subset as well, and it is showing.... I'm trying to find out if the two sets of jobs were sent thru queue Z and queue -MINI-.

**Comment by Jnesselr** [comment]
Does queue Z show Z3 and Z4?

**Comment by StanleyT** [comment]
yes
and both pod Y and Z were sent through -MINI-. now to make this all more confusing pod Y started showing working jobs...

**Comment by Jnesselr** [comment]
That shouldn't be possible. The job can only currently reference one queue
at a time. That's. Well... Confusing.

**Comment by StanleyT** [comment]
well, good news then. currently all queues are reporting correctly. MINI is not showing any while pod Y and Z are showing their corresponding jobs.

**Comment by Jnesselr** [comment]
Okay. That's good I think. If you see the issue again, please take
screenshots of the queues to show the duplication.

**Comment by StanleyT** [comment]
will do
