### ISSUE TITLE
Status and local install

### ISSUE THREAD

**Issue by boelle** [Hoektronics/BotQueue#161]
Hi

are there any guides on how to do a local install (at webhostning company) ?
is amazon a requirement?

and what is the project status?

**Comment by Jnesselr** [comment]
(cross-posting from mailing list)

BotQueue v1 was written for PHP 5 and Python 2. I have no illusions that it'll work as written. I was working on BotQueue v2 for some time, but as this isn't a paid project I have been forced to focus on other things. I consider the project not dead, but not exactly alive either. More or less, it's in stasis until I find a rather large chunk of free time.
For what it's worth, local install will always be possible and amazon will never be a requirement, both for BotQueue v1 and BotQueue v2. BotQueue v1 is definitely more tightly integrated to Amazon though, but I had a local install running for years completely off of Amazon. Still, I would not recommend trying to get v1 installed as I will not be able to respond to any support questions.
~ Justin Nesselrotte
